TX-260 | AppUUID added in the ExecuteUUID Method
3CLogicInc/go-eventsocket pull request #1
Opened 2020-08-21 06:02 UTC by chetan3clogic

2020-08-21 06:50 UTC, ravindrachaurasia approved these changes

2020-08-21 14:07 UTC, anshumanr requested changes

2020-08-21 14:07 UTC, anshumanr commented on eventsocket/eventsocket.go
> +
and if we cannot send blank `appUUID`, how about this -

```
func (h *Connection) ExecuteUUID(uuid, appName, appArg, appUUID string) (*Event, error) {

	msg := MSG{
		"call-command":     "execute",
		"execute-app-name": appName,
		"execute-app-arg":  appArg,
	}
	if appUUID != "" {
		msg["event-uuid"] = appUUID
	}

	return h.SendMsg(msg, uuid, "")
}
```

2020-08-21 14:07 UTC, anshumanr commented on eventsocket/eventsocket.go
> +			"event-uuid":       appUUID,
what are the side-effects if appUUID is blank but we add it anyway?

2020-08-24 08:20 UTC, chetan3clogic commented on eventsocket/eventsocket.go
> +			"event-uuid":       appUUID,
When we send an empty `event-uuid : ""` FreeSWITCH will auto-generate an uuid for that specific application.

2020-08-24 13:14 UTC, anshumanr approved these changes

2020-08-24 13:14 UTC, merged